# Generated by Django 4.2 on 2025-04-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_biblioteca_paginas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biblioteca',
            new_name='Livros',
        ),
    ]
